# Generated by Django 4.2.11 on 2025-06-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default=1, upload_to='category_images'),
            preserve_default=False,
        ),
    ]
