# Generated by Django 4.2.11 on 2025-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
